apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sre-asset-monitor
spec:
  concurrencyPolicy: Replace
  schedule: "0 */1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: sre-asset
            image: https://hub.docker.com/repository/docker/abhinavgupta96/sre-assets:v11
            resources:
              requests:
                memory: "1Gi"
                cpu: "250m"
              limits:
                memory: "2Gi"
                cpu: "500m"
            volumeMounts:
                - mountPath: "/assets/configs"
                  name: vol-ini
          imagePullSecrets:
          - name: harbor-cloud-registry
          volumes:
          - name: vol-ini
            secret:
              secretName: sre-asset-secret
          restartPolicy: Never         